spring.application.name=portfolio-backend
server.port=8080

management.endpoints.web.exposure.include=health,info
spring.jackson.date-format=yyyy-MM-dd

# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:portfolio}
spring.datasource.username=${PGUSER:portfolio}
spring.datasource.password=${PGPASSWORD:portfolio}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Debug logging
logging.level.root=INFO
logging.level.com.atelier.portfolio=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.properties.hibernate.format_sql=true
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:portfolio}
spring.liquibase.user=${PGUSER:portfolio}
spring.liquibase.password=${PGPASSWORD:portfolio}
